# Generated by Django 2.0.3 on 2018-03-23 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profilegeolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='profilegeolocation',
            name='profile',
        ),
        migrations.AddField(
            model_name='profilegeolocation',
            name='profileAddress',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileAddress'),
            preserve_default=False,
        ),
    ]
