# Generated by Django 2.0.3 on 2018-03-23 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180322_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilegeolocation',
            name='profileAddress',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilegeolocation',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProfileAddress',
        ),
    ]
