# Generated by Django 2.0.3 on 2018-03-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180322_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
