# Generated by Django 2.0.3 on 2018-03-23 03:59
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profilehub'),
    ]

    operations = [
        UnaccentExtension()
    ]
