# Generated by Django 2.0.3 on 2018-03-23 04:05
from django.contrib.postgres.operations import UnaccentExtension

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180322_2359'),
    ]

    operations = [
        UnaccentExtension()
    ]
