# Generated by Django 2.0.3 on 2018-04-03 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20180402_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilehub',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_hub', to='hubs.Hub'),
        ),
        migrations.AlterField(
            model_name='profilehub',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
