# Generated by Django 2.0.3 on 2018-04-11 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20180402_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilewallet',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_wallet', to='profiles.Profile'),
        ),
    ]
