# Generated by Django 2.0.3 on 2018-03-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_isvalidated'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('CP', 'Community Project'), ('CO', 'Community Offer'), ('BO', 'Community Project and Community Offer')], default='BO', max_length=2),
        ),
    ]
