# Generated by Django 2.0.3 on 2018-03-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='project_volunteers_roles',
            old_name='Role',
            new_name='role',
        ),
        migrations.AddField(
            model_name='project_status',
            name='is_executed',
            field=models.BooleanField(default=False),
        ),
    ]
