# Generated by Django 2.0.3 on 2018-03-24 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180323_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_hub',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub_project', to='projects.Project'),
        ),
    ]
