# Generated by Django 2.0.3 on 2018-03-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180324_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_projects', to='profiles.Profile'),
        ),
    ]
