# Generated by Django 2.0.3 on 2018-03-25 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180325_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_geolocation',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
