# Generated by Django 2.0.3 on 2018-03-25 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180325_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_geolocation',
            name='project_hub',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='projects.Project_Hub'),
        ),
    ]
