# Generated by Django 2.0.3 on 2018-03-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20180325_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_geolocation',
            name='project_hub',
        ),
        migrations.DeleteModel(
            name='Project_Geolocation',
        ),
    ]
