# Generated by Django 2.0.3 on 2018-03-26 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20180325_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_attendees',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project_attendees',
            name='seats',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='project_attendees_registration',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project_Attendees'),
        ),
        migrations.AlterField(
            model_name='project_volunteers',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project_volunteers_registration',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project_Volunteers'),
        ),
        migrations.AlterField(
            model_name='project_volunteers_roles',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers_roles', to='projects.Project'),
        ),
    ]
