# Generated by Django 2.0.3 on 2018-03-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20180325_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_status',
            name='isValidated',
            field=models.BooleanField(default=False),
        ),
    ]
