# Generated by Django 2.0.3 on 2018-03-26 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_status_isvalidated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_attendees_registration',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees_registration', to='projects.Project_Attendees'),
        ),
        migrations.AlterField(
            model_name='project_status',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project_volunteers_registration',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_registration', to='projects.Project_Volunteers'),
        ),
        migrations.AlterField(
            model_name='project_volunteers_roles_registration',
            name='project_roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_registration', to='projects.Project_Volunteers_Roles'),
        ),
    ]
