# Generated by Django 2.0.3 on 2018-03-26 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20180325_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_volunteers_roles_registration',
            old_name='project_roles',
            new_name='project',
        ),
    ]
