# Generated by Django 2.0.3 on 2018-03-26 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20180325_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_attendees_registration',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_attendee', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='project_volunteers_registration',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_volunteer', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='project_volunteers_roles_registration',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_volunteer_role', to='profiles.Profile'),
        ),
    ]
