# Generated by Django 2.0.3 on 2018-03-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20180325_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_volunteers_roles',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project_volunteers_roles_registration',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='project_volunteers_roles_registration',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='Category', max_length=50),
        ),
        migrations.AddField(
            model_name='project_volunteers',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project_volunteers',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_volunteers',
            name='is_general_volunteering',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project_volunteers',
            name='minimum_registration',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project_volunteers',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project_volunteers',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_volunteers',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project_volunteers_registration',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers_registration', to='projects.Project_Volunteers'),
        ),
        migrations.DeleteModel(
            name='Project_Volunteers_Roles',
        ),
        migrations.DeleteModel(
            name='Project_Volunteers_Roles_Registration',
        ),
    ]
