# Generated by Django 2.0.3 on 2018-03-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20180327_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_volunteers',
            name='project',
        ),
        migrations.AddField(
            model_name='project_volunteers',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='projects.Project'),
        ),
    ]
