# Generated by Django 2.0.3 on 2018-03-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20180329_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_volunteers',
            name='role',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
    ]
