# Generated by Django 2.0.3 on 2018-03-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_project_answer_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_answer_discussion',
            name='name',
        ),
        migrations.AddField(
            model_name='project_discussion',
            name='title',
            field=models.CharField(default='Title', max_length=100),
            preserve_default=False,
        ),
    ]
