# Generated by Django 2.0.3 on 2018-03-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20180330_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_answer_discussion',
            name='comment',
        ),
        migrations.AddField(
            model_name='project_answer_discussion',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_discussion_project', to='projects.Project_Discussion'),
        ),
        migrations.AlterField(
            model_name='project_discussion',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_project', to='projects.Project'),
        ),
    ]
