# Generated by Django 2.0.3 on 2018-03-30 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_project_discussion_project_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_discussion',
            name='project',
            field=models.ForeignKey(default=62, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_project', to='projects.Project'),
            preserve_default=False,
        ),
    ]
