# Generated by Django 2.0.3 on 2018-03-30 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20180330_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_answer_discussion',
            name='discussion_ref',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_answer_discussion',
            name='discussion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_discussion_project', to='projects.Project_Discussion'),
            preserve_default=False,
        ),
    ]
