# Generated by Django 2.0.3 on 2018-04-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20180402_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_attendees',
            name='minimum_registration',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='project_volunteers',
            name='minimum_registration',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
