# Generated by Django 2.0.3 on 2018-04-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20180407_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sub_category',
            field=models.CharField(choices=[('Cul_con', 'Concert/Show/Presentation'), ('Cul_oth', 'Other activity'), ('Edu_kno', 'Knowledge'), ('Edu_ski', 'Skills share'), ('Edu_oth', 'Other activity'), ('Hea_phy', 'Physical fitness'), ('Hea_emo', 'Emotional well-being'), ('Hea_oth', 'Other activity'), ('Soc_foo', 'Food security'), ('Soc_chi', 'Childcare'), ('Soc_eld', 'Eldercare'), ('Soc_ani', 'Animalcare'), ('Soc_oth', 'Other activity'), ('Env_gar', 'Gardening'), ('Env_cle', 'Cleanups'), ('Env_oth', 'Other activity'), ('Oth_oth', 'Other activity')], default='Oth_oth', max_length=7),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Cul', 'Culture and Recreation'), ('Edu', 'Education'), ('Hea', 'Health'), ('Soc', 'Social Services'), ('Env', 'Environment'), ('Oth', 'Other')], default='Oth', max_length=3),
        ),
    ]
