# Generated by Django 2.0.3 on 2018-05-04 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20180411_1920'),
        ('hubs', '0004_hubdiscussion'),
        ('projects', '0037_auto_20180407_1306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_Answer_Discussion',
            new_name='ProjectAnswerDiscussion',
        ),
        migrations.RenameModel(
            old_name='Project_Attendees',
            new_name='ProjectAttendees',
        ),
        migrations.RenameModel(
            old_name='Project_Attendees_Registration',
            new_name='ProjectAttendeesRegistration',
        ),
        migrations.RenameModel(
            old_name='Project_Discussion',
            new_name='ProjectDiscussion',
        ),
        migrations.RenameModel(
            old_name='Project_Hub',
            new_name='ProjectHub',
        ),
        migrations.RenameModel(
            old_name='Project_isValidated',
            new_name='ProjectIsValidated',
        ),
        migrations.RenameModel(
            old_name='Project_Status',
            new_name='ProjectStatus',
        ),
        migrations.RenameModel(
            old_name='Project_Volunteers',
            new_name='ProjectVolunteers',
        ),
        migrations.RenameModel(
            old_name='Project_Volunteers_Registration',
            new_name='ProjectVolunteersRegistration',
        ),
    ]
