# Generated by Django 2.0.3 on 2018-08-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20180624_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='place_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
