# Generated by Django 2.0.3 on 2018-03-24 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demands', '0001_initial'),
        ('projects', '0004_auto_20180323_1346'),
        ('profiles', '0009_profilewallet'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('debit', models.PositiveIntegerField(blank=True, null=True)),
                ('credit', models.PositiveIntegerField(blank=True, null=True)),
                ('balance', models.PositiveIntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('OF', 'Offer'), ('DE', 'Demand'), ('CR', 'Creation')], max_length=2)),
                ('transaction_id', models.PositiveIntegerField()),
                ('profile_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user', to='profiles.Profile')),
                ('profile_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user', to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_isCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_isDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demands.Demand')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_isOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.Offer')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='operations',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.Transaction'),
        ),
    ]
