# Generated by Django 2.0.3 on 2018-05-04 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0007_auto_20180503_2129'),
        ('offers', '0009_auto_20180430_2202'),
        ('projects', '0037_auto_20180407_1306'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction_isOffer',
            new_name='TransactionIsCreation',
        ),
        migrations.RenameModel(
            old_name='Transaction_isDemand',
            new_name='TransactionIsDemand',
        ),
        migrations.RenameModel(
            old_name='Transaction_isCreation',
            new_name='TransactionIsOffer',
        ),
        migrations.RemoveField(
            model_name='transactioniscreation',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='transactionisoffer',
            name='project',
        ),
        migrations.AddField(
            model_name='transactioniscreation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='transactionisoffer',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.Offer'),
        ),
    ]
