# Generated by Django 2.0.3 on 2018-07-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180716_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileIsCreated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='termsIsAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
