# Generated by Django 2.0.3 on 2018-07-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180716_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='olderThanSixteen',
            field=models.BooleanField(default=False),
        ),
    ]
