# Generated by Django 2.0.3 on 2018-03-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hubs', '0004_hubdiscussion'),
        ('profiles', '0008_auto_20180323_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('number', models.CharField(blank=True, max_length=10)),
                ('street', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('demand_type', models.CharField(choices=[('CAPS', 'Community Actions Points'), ('TROC', 'Barter with what you want'), ('GIVE', 'Looking for free')], default='CAPS', max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Demand_CAPS_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.PositiveSmallIntegerField(default=0)),
                ('demand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demands.Demand')),
            ],
        ),
        migrations.CreateModel(
            name='Demand_Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('demand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demands.Demand')),
            ],
        ),
        migrations.CreateModel(
            name='Demand_Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('demand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demands.Demand')),
                ('hub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hubs.Hub')),
            ],
        ),
        migrations.CreateModel(
            name='Demand_TROC_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.CharField(default='Bag of Senzu Bean, Please Update', max_length=200)),
                ('demand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demands.Demand')),
            ],
        ),
    ]
