# Generated by Django 2.0.3 on 2018-03-26 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0003_auto_20180325_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand_hub',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='hubs.Hub'),
        ),
    ]
