# Generated by Django 2.0.3 on 2018-03-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0004_auto_20180325_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand_caps_price',
            name='demand',
        ),
        migrations.RemoveField(
            model_name='demand_geolocation',
            name='demand',
        ),
        migrations.RemoveField(
            model_name='demand_troc_price',
            name='demand',
        ),
        migrations.AddField(
            model_name='demand',
            name='price_CAPS',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='price_barter',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Demand_CAPS_Price',
        ),
        migrations.DeleteModel(
            name='Demand_Geolocation',
        ),
        migrations.DeleteModel(
            name='Demand_TROC_Price',
        ),
    ]
