# Generated by Django 2.0.3 on 2018-03-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0005_auto_20180325_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='demand_type',
        ),
        migrations.AddField(
            model_name='demand',
            name='is_BARTER',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='is_CAPS',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='is_GIVE',
            field=models.BooleanField(default=True),
        ),
    ]
