# Generated by Django 2.0.3 on 2018-05-04 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0004_hubdiscussion'),
        ('demands', '0006_auto_20180327_0944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demand_Hub',
            new_name='DemandHub',
        ),
    ]
