# Generated by Django 2.0.3 on 2018-03-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_highlighted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_offers', to='profiles.Profile'),
        ),
    ]
