# Generated by Django 2.0.3 on 2018-03-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20180324_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='highlighted',
            field=models.TextField(blank=True),
        ),
    ]
