# Generated by Django 2.0.3 on 2018-03-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20180324_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='highlighted',
        ),
    ]
