# Generated by Django 2.0.3 on 2018-03-26 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_remove_offer_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer_geolocation',
            name='offer',
        ),
        migrations.AddField(
            model_name='offer_hub',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='offer_hub',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='offer_hub',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='hubs.Hub'),
        ),
        migrations.DeleteModel(
            name='Offer_Geolocation',
        ),
    ]
