# Generated by Django 2.0.3 on 2018-03-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_auto_20180325_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer_caps_price',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offer_troc_price',
            name='offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='price_CAPS',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='price_barter',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Offer_CAPS_Price',
        ),
        migrations.DeleteModel(
            name='Offer_TROC_Price',
        ),
    ]
