# Generated by Django 2.0.3 on 2018-03-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20180325_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offer_type',
        ),
        migrations.AddField(
            model_name='offer',
            name='is_BARTER',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_CAPS',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_GIVE',
            field=models.BooleanField(default=True),
        ),
    ]
