# Generated by Django 2.0.3 on 2018-05-04 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0004_hubdiscussion'),
        ('offers', '0009_auto_20180430_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer_Hub',
            new_name='OfferHub',
        ),
    ]
